[workspace]
members = [
  "cli",
  "helper",
  "tools/xtask",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
authors = ["Martin Calander"]
license = "MIT"
repository = "https://github.com/soupmasters/AsepriteExtensionManager"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

[profile.dev]
debug = 1
